# Autogenerated file
def render(hours):
    yield """
<!DOCTYPE html>
<html>
    <head>
        <meta charset=\"UTF-8\" />
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
        <title>AutoCAT</title>
        <link rel=\"stylesheet\" href=\"static/css/index.css\" />
        <script src=\"static/js/index.js\"></script>
    </head>
    <body>
        <h1>AutoCAT</h1>
        <form onsubmit=\"submitForm(event)\">
            <h2>Scheduler</h2>
            <ul class=\"scheduler\">
            """
    for hour in hours:
        yield """
                <li>
                <input name=\"meal\" type=\"text\" value=\""""
        yield str(hour.name)
        yield """\" />
                <input name=\"time\" type=\"time\" value=\""""
        yield str(hour.atTime)
        yield """\" />
                <input name=\"quantity\" type=\"number\" value=\""""
        yield str(hour.quantity)
        yield """\" /></li>
            """
    yield """
            </ul>
            <button class=\"submit button button-primary\" onclick=\"submit\">Guardar</button>
        </form>
        <div class=\"actions\">
            <div class=\"button-wrap\">
                <a href=\"#\" class=\"button button-circle button-action\" onclick=\"serveFeed()\">Servir comida</a>
            </div>
        </div>
    </body>
</html>"""
