esphome:
  name: fraction-feeder
  friendly_name: fraction-feeder

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

servo:
  - id: impeller_servo
    output: gpio_5
    min_level: 0.025  # Equivalent to 500 µs
    max_level: 0.125  # Equivalent to 2500 µs
    auto_detach_time: 1s
    transition_length: 5s
    restore: True

output:
  - platform: ledc
    pin: GPIO5
    id: gpio_5
    frequency: 50 Hz # MUST BE 50Hz

number:
  - platform: template
    id: servo_control
    name: "Servo Control"
    restore_value: True
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: True
    set_action:
      then:
        - servo.write:
            id: impeller_servo
            level: !lambda 'return x / 100.0;'

button:
  - platform: template
    name: "Feed"
    on_press:
      then:
        - lambda: |-
            int current_value = id(servo_control).state;
            int target_value = (current_value >= 0) ? -100 : 100;
            id(servo_control).make_call().set_value(target_value).perform();
  - platform: restart
    name: "Fraction Feeder Restart"
